FROM --platform=linux/ppc64le ppc64le/alpine:latest

COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh

ADD ./upx/ppc64le/upx /usr/local/bin/