# Use a minimal Alpine Linux image as the base
FROM gfunkmonk1/mipsel-alpine:latest

COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh

ADD ./upx/mipsel/upx /usr/local/bin/