FROM i386/alpine:latest

COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
ENTRYPOINT ["linux32", "--"]

ADD ./upx/i386/upx /usr/local/bin/