FROM --platform=linux/arm64 arm64v8/alpine:latest

COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh

ADD ./upx/arm64/upx /usr/local/bin/
